server:
  port: 8181
  application:
    name: payments-service

# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: catrip
    password: 200605663*k3p
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer